### ISSUE TITLE
[1.7.10 #54] /nick changes the name of the irc bot, not the player and unable to change irc name.

### ISSUE THREAD

**Issue by Fogger** [blay09/EiraIRC#117]
First time in 1.7.10 since 1.6.4

Upon entering my world, I used '/nick MyName' as I always do, but was astonished to see that I actually renamed the irc bot.

Server has Forge Essentials, which was my intended target of the command.

Also, using '/irc nick MyName' did not change my name to appear as 'MyName' in irc, no matter what I do, it remains my real in-game name.

Is this intended, am I missing something?

**Comment by blay09** [comment]
It's kinda intended, but also kinda not. There's a config option called "registerShortCommands" that registers aliases for the /irc join, /irc nick, etc. commands. Setting that to false will make EiraIRC stop overwriting Forge Essentials command. The default value might be 'true', I'll have a look at that and change it to false, since there's no real reason for servers to use it.

/irc nick is basically the same as /servirc nick (and thus, /nick), just ran in the client instead. At the moment, all that command does is rename actual IRC bots. If you want a different name to appear in the chat that the server bridges to IRC, you'll have to stick to the /irc alias command for now (which is OP-only as it also changes the name that appears in Minecraft chat). 

As of now, I'm afraid there's no way for players to have different IRC nicks than IG nicks. I was doing some plans for that (see #13), but there wasn't any demand yet. I'll make sure it gets added in EiraIRC 2.8.

**Comment by Fogger** [comment]
Thanks, the registerShortCommands=false solved the /nick issue.

However, I tried the /irc alias both in-game (as Op) and Console in the formats

    /irc alias
    /irc alias <NewName>
    /irc alias <OldName> <NewName>

but all I got was

    [net.blay09.mods.eirairc.command.base.IgnoreCommand:func_71515_b:44]: Ignoring command irc with 1 arguments
    [net.blay09.mods.eirairc.command.base.IgnoreCommand:func_71515_b:44]: Ignoring command irc with 2 arguments
    [net.blay09.mods.eirairc.command.base.IgnoreCommand:func_71515_b:44]: Ignoring command irc with 3 arguments

**Comment by blay09** [comment]
Indeed, /servirc (or /sirc in short) is the server variant of the command.

Haha, will make sure to include the improved nick command in the next version ;)

**Comment by Fogger** [comment]
You're the best! :)
