### ISSUE TITLE
URLs not working on left click 1.7.10 build 1.7.52 and 1.7.56

### ISSUE THREAD

**Issue by plazia** [blay09/EiraIRC#135]
Whenever someone posts a URL/hyperlink in the chat you can't left click it and open in default URL handler (such as browser or what not)

This used to work in the build I used in 1.6.4 EiraIRC.

**Comment by blay09** [comment]
This is actually a bug in Vanilla Minecraft: https://bugs.mojang.com/browse/MC-30864

EiraIRC mc1.7.10 v2.8.x should fix this issue at least for IRC chat. For Vanilla chat, EiraIRC will only fix it if it's installed on the server as of now. The latest version of the 2.8 branch can be found on my jenkins, so if you want this fixed quickly I suggest you switch over to that:

http://blay09.net:8080/jenkins/job/EiraIRC%201.7.10%20Update%20v2.8%20%28alpha%29/

It's unlikely that I'll backport this fix to the v1.7 builds since v2.8 will replace them as new recommended version pretty soon anyways.
