### ISSUE TITLE
Disable EiraIRC through server

### ISSUE THREAD

**Issue by 016Nojr** [blay09/EiraIRC#136]
Would it be possible to add something to EiraIRC which would make server owners able to disable the EiraIRC in the client. Some owners doesnt want it, and when they download it they would automatically get it, and they would have needed to restarted the whole pack to remove it.

**Comment by blay09** [comment]
I don't quite see the point - how does it matter to server owners? Which features of EiraIRC in particular do you want disabled on player clients?

In any case, it would still be a voluntary choice for the user. If I implement this, it'll make use of the same UI as the Redirect dialog, so that users can (always) accept or refuse.

**Comment by blay09** [comment]
Closed for now since there was no response for nearly two months. Feel free to re-open when it becomes relevant again.
