### ISSUE TITLE
[Thread-6/INFO]: â��123â�� is not a valid nickname.

### ISSUE THREAD

**Issue by radien** [blay09/EiraIRC#164]
Not sure how to fix this, i've tried several different nicknames, i've deleted the file and recreated it. 
I've got forge-1.8-11.14.0.1299 & eirairc-mc1.8-v1.7.5

**Comment by blay09** [comment]
I'm already in bed so I can only guess right now, but make sure that nickPrefix and nickSuffix are empty, and that you change all nicks (global AND server-specific one). Also, if it's the default %USERNAME%, it might be some mod adding a name color in a weird way in which case it should help just putting your username there directly. I'll have a closer look tomorrow if you don't get it solved till then.

Another thing would be ensuring that eirairc.cfg is encoded as UTF-8. I guess there could be problems otherwise if your nick contains special characters, but I'm not sure.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: radien <notifications@github.com> </div><div>Datum:25.02.2015  21:56  (GMT+01:00) </div><div>An: blay09/EiraIRC <EiraIRC@noreply.github.com> </div><div>Betreff: [EiraIRC] [Thread-6/INFO]: â��123â�� is not a valid nickname. (#164) </div><div>
</div>Not sure how to fix this, i've tried several different nicknames, i've deleted the file and recreated it. 
I've got forge-1.8-11.14.0.1299 & eirairc-mc1.8-v1.7.5

**Comment by radien** [comment]
I figured it out shortly after posting this. when i was getting the error the config line was this: S:nick="123" 
but once i changed it to S:nick=123 it worked.

I copied the "servers { }'s bit from http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291581-eirairc-irc-twitch-screenshots-and-more

**Comment by blay09** [comment]
Ah, so it's a bug with EiraIRC after all then. Will fix it for the jenkins version later today.

Glad you got it sorted out!

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: radien <notifications@github.com> </div><div>Datum:25.02.2015  22:38  (GMT+01:00) </div><div>An: blay09/EiraIRC <EiraIRC@noreply.github.com> </div><div>Cc: Christopher Baker <blay09@hotmail.de> </div><div>Betreff: Re: [EiraIRC] [Thread-6/INFO]: â��123â�� is not a valid nickname. (#164) </div><div>
</div>I figured it out shortly after posting this. when i was getting the error the config line was this: S:nick="123" 
but once i changed it to S:nick=123 it worked.

I copied the "servers { }'s bit from http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291581-eirairc-irc-twitch-screenshots-and-more

**Comment by radien** [comment]
Would EiraIRC effect any entity ticking? we're running 11.14.1.1332 with just EiraIRC and the server keeps dying with en error "ticking entity" before i asked for help from forge i figured i'd see if it was something in your code

**Comment by blay09** [comment]
I highly doubt this is EiraIRC, since it neither adds entities or messes with them in any way. We can be sure if you show me the crashlog.

**Comment by radien** [comment]
Here's the Crash report. http://pastebin.com/ZwJRVwSU

**Comment by blay09** [comment]
When does the crash happen? On login? On relogin? While playing?

I've looked at the corresponding Minecraft code and it looks like it's ticking the entity and sending chunk data before the FML handshake is done. I wouldn't know how EiraIRC could be causing this so I assume it's a Forge/FML issue.
