### ISSUE TITLE
Severe incompatibility with Aether II

### ISSUE THREAD

**Issue by BBoldt** [blay09/EiraIRC#177]
So, the Aether II has it's own menu that shows up when you are in the chat menu, it looks like this:
![](http://i.imgur.com/e8dZ1c5.png)

Problem is, your chat menu overrides this completely, causing the player to be unable to access certain critical features of the Aether II mod. Things such as multiplayer dungeon raiding, cloud network options, and other gui settings.

Now, if I may make a suggestion, could you have an option so the chat doesn't get used at all when using EiraIRC? 
So if you press tab to switch channels, it would say something like "switching to #channel" or "switching to minecraft chat" rather than showing what channel you are connected to in the top left.
If that's a bad idea or impossible, i'm sorry. I'm just trying to think of simple solutions for using these mods together without conflict. 

I don't know if there may be a way for aether and eirairc to 'share' the chat and both of them have their gui displayed, but that would probably be ideal.

**Comment by blay09** [comment]
Note: This fix won't actually make it compatible since EiraIRC still needs it's ClientChatEvent fired somehow. I totally forgot about that part of my chat override, so all this 'fix' did was make EiraIRC not work properly anymore.

As things stand, I assume Aether will follow killjoy's advice and switch their minor changes to GUI events, which should take care of things with Aether II. Will remove the auto-setting of chatNoOverride for Aether II again and have it happen for TabbyChat instead (since that one is actually supposed to take over the whole chat).

https://github.com/gildedgames/aether-issues/issues/478
