### ISSUE TITLE
Clickable links don't work for things posted in minecraft chat

### ISSUE THREAD

**Issue by BBoldt** [blay09/EiraIRC#267]
But they do work for things posted from IRC.

**Comment by blay09** [comment]
This is [MC-30864](https://bugs.mojang.com/browse/MC-30864), a vanilla bug. EiraIRC currently only fixes this issue for things from IRC chat or when installed on the server.

I probably have a simple way to make it work (and by make it work I mean fix the vanilla bug) on the client-side only for Minecraft chat, might look into that again.

**Comment by blay09** [comment]
Actually, I just saw this should have been [fixed by Minecraft Forge](https://github.com/MinecraftForge/MinecraftForge/commit/51271dcc3a7bb8c2f05df71ef002b1d26240b4eb) already.

Gonna have to check if something on EiraIRC's client-side is breaking it or if your server owner is just super out of date on Forge.

**Comment by blay09** [comment]
Just tested on a Forge 10.13.3.1408 with no mods and a client with only EiraIRC and I could click links fine, even without the hacky fix I unnecessarily made.

Either your server's Forge version is way out of date or you have some other mod installed that's breaking links.

**Comment by blay09** [comment]
Hey, you said you had asielib installed, right?

There's your culprit. Unless I've missed something in their code, they're breaking links.
